"""tenant settings

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###

    # New default levels: soft triggers and input signals are critical.
    op.execute("UPDATE alarms SET priority = 1 WHERE state = 'new' AND event_type IN ('softTrigger', 'cameraInput')")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('settings')

    # ### end Alembic commands ###
