"""alarm level source

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_source', sa.String(length=20), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.drop_column('level_source')

    # ### end Alembic commands ###
